export default {
  GOOGLEAPI: 'https://maps.googleapis.com/maps/api/geocode/json?latlng=',
  KEY: '&key=',
  TEXT: 'text',
  NUMBER: 'number',
  EDIT_LOCATION_INFORMATION: 'Location Information',
  LOCATION: 'Home Address',
  ENTER_FULL_ADDRESS: 'Search with city,post code',
  ADDRESS: 'address',
  ENTER_APARTMENT_NAME: 'Flat / Apartment No / Street Address',
  STREET_ADDRESS: 'streetAddress',
  PLEASE_ENTER_APARTMENT_NAME: 'Please enter Apartment name',
  ENTER_HOUSE_NO: 'Colony / Locality',
  PLEASE_ENTER_HOUSE_NO: 'Please enter House No.',
  HOUSE_NO: 'houseNo',
  ENTER_ZIPCODE: 'Zipcode',
  PLEASE_ENTER_ZIPCODE: 'Please enter Zipcode',
  ZIPCODE: 'zipcode',
  ENTER_DISTANCE: 'Distance (miles)',
  PLEASE_ENTER_DISTANCE: 'Please enter distance',
  DISTANCE: 'distance',
};
