export default {
  ALL: 'All',
  CUSTOMER_REQUESTED: 'CUSTOMER_REQUESTED',
  CHEF_ACCEPTED: 'CHEF_ACCEPTED',
  CHEF_REJECTED: 'CHEF_REJECTED',
  CANCELLED_BY_CHEF: 'CANCELLED_BY_CHEF',
  CANCELLED_BY_CHEF_OR_CHEF_REJECTED: 'CANCELLED_BY_CHEF/CHEF_REJECTED',
  CANCELLED_BY_CUSTOMER: 'CANCELLED_BY_CUSTOMER',
  PAYMENT_PENDING: 'PAYMENT_PENDING',
  PAYMENT_FAILED: 'PAYMENT_FAILED',
  YOU_HAVE_COMPLETED: 'You have Completed',
  COMPLETED: 'COMPLETED',
  Complete: 'Complete',
  Completed: 'Completed',
  UPCOMING: 'Upcoming',
  REQUESTED: 'Requested',
  CANCELLED: 'Cancelled',
  PAYMENT_OPTION: 'Payment Pending / Draft',
  PAYMENT_FAILED_OPTION: 'Payment Failed',
  TRANSFER_FAILED_TAB: 'Transfer Failed',
  TRANSFER_FAILED: 'TRANSFER_FAILED',
  AMT_TRANSFER_FAILED: 'AMOUNT_TRANSFER_FAILED',
  AMT_TRANSFER_SUCCESS: 'AMOUNT_TRANSFER_SUCCESS',
  REFUND_AMOUNT_SUCCESS: 'REFUND_AMOUNT_SUCCESS',
  REFUND_AMOUNT_FAILED: 'REFUND_AMOUNT_FAILED',
  REFUND_AMOUNT_SUCCESS_TAB: 'Refund Amount Success',
  REFUND_AMOUNT_FAILED_TAB: 'Refund Amount Failed',
  CANCEL: 'Cancel',
  Rejected: 'Rejected',
  ACCEPTED: 'Accepted',
  Reject: 'Reject',
  ACCEPT: 'Accept',
  PAY_NOW: 'Pay Now',
  TAB1: 'tab1',
  TAB2: 'tab2',
  TAB3: 'tab3',
  TAB4: 'tab4',
  TAB5: 'tab5',
  TAB6: 'tab6',
  TAB7: 'tab7',
  TAB8: 'tab8',
  TAB9: 'tab9',
  NO_DATA_AVAILABLE: 'No data Available',
  chefDefaultImage: require('../../images/mock-image/default_chef_profile.png'),
  customerDefaultImage: require('../../images/mock-image/rockoly-logo.png'),
  noDataImage: require('../../images/mock-image/no-data.png'),
  FROM_TIME: 'From Time: ',
  TO_TIME: 'To Time: ',
  CANCELLED_BY_CHEF_OR_CHEF_REJECTED_TEXT: 'You have Cancelled Booking / You have Rejected Booking',
  CANCELLED_BY_CHEF_OR_CHEF_REJECTED_TEXT1: 'Cancelled by chef/Rejected by chef',
  CANCELLED_BY_CUSTOMER_TEXT: 'Cancelled by Customer',
  CANCELLED_BY_CUSTOMER_TEXT1: 'You have Cancelled Booking',
  AMT_NOT_TRANSFERED_YET: 'Amount not transfered yet',
  AMT_NOT_TRANSFERED: 'Amount not transfered',
  AWAITING_FOR_CHEF: 'Awaiting For Chef',
  FROM_DATE: 'From Date:',
  TO_DATE: 'To Date',
  ADD_FROM_DATE: 'Enter Start Date',
  ADD_TO_DATE: 'Enter End Date',
  SUBMIT: 'Submit',
  SUBMIT_FEEDBACK: 'Submit your feedback',
  PAYMENT_COMPLETED: 'Payment completed successfully',
  BOOKING_COMPLETED: 'Booking completed successfully',
  COMPLETED_ALERT: 'Are you sure you want to Complete?',
  ACCEPT_ALERT: 'Are you sure you want to accept this request?',
  REJECT_ALERT: 'Are you sure you want to reject this request?',
  CANCEL_ALERT: 'Are you sure you want to cancel this request?',
  NO: 'No',
  YES: 'Yes',
  STRIPEID_MISSING_MSG: 'Please add your card for payment updation!',
  COMPLETED_VALIDATION: `You can't complete booking before booking start date!`,
  CHEF_REQUESTED_AMOUNT: 'Chef Requested Amount',
};
