export default {
  HOUR: '/hour',
  FULL_STAR: require('../../images/mock-image/star-yellow.png'),
  EMPTY_STAR: require('../../images/mock-image/star-empty.png'),
  FULL_NAME: 'Full Name:',
  ADDRESS: 'Address:',
  BOOKING_PRICE: 'BOOKING PRICE',
  BOOKING_TIME_AND_DATE: 'BOOKING TIME AND DATE',
  BOOKING_STATUS: 'Booking Status',
  YOUR_REASON: 'Reason',
  ALL: 'All',
  CUSTOMER_REQUESTED: 'CUSTOMER_REQUESTED',
  CHEF_ACCEPTED: 'CHEF_ACCEPTED',
  CHEF_ACCEPTED_TEXT: 'Chef Accepted',
  CHEF_REJECTED: 'CHEF_REJECTED',
  CANCELLED_BY_CHEF: 'CANCELLED_BY_CHEF',
  REFUND_AMOUNT_SUCCESS: 'REFUND_AMOUNT_SUCCESS',
  REFUND_AMOUNT_FAILED: 'REFUND_AMOUNT_FAILED',
  CANCELLED_BY_CHEF_OR_CHEF_REJECTED: 'Cancelled by chef/Rejected by chef',
  CANCELLED_BY_CHEF_OR_CHEF_REJECTED_TEXT: 'You have Cancelled Booking / You have Rejected Booking',
  CANCELLED_BY_CUSTOMER: 'CANCELLED_BY_CUSTOMER',
  CANCELLED_BY_CUSTOMER_TEXT: 'Cancelled by Customer',
  CANCELLED_BY_CUSTOMER_TEXT1: 'You have Cancelled Booking',
  COMPLETED: 'COMPLETED',
  Complete: 'Complete',
  Completed: 'Completed',
  UPCOMING: 'Upcoming',
  CANCEL: 'Cancel',
  ACCEPT: 'Accept',
  Reject: 'Reject',
  chefDefaultImage: require('../../images/mock-image/default_chef_profile.png'),
  customerDefaultImage: require('../../images/mock-image/rockoly-logo.png'),
  noDataImage: require('../../images/mock-image/no-data.png'),
  COMPLETED_BY_CUSTOMER: 'Completed by Customer',
  COMPLETED_BY_CHEF: 'Completed by Chef',
  ACCEPTED_BY_CHEF: 'Accepted by chef',
  REQUESTED_BY_CUSTOMER: 'Requested by Customer',
  AWAITING_FOR_CHEF: 'Awaiting For Chef',
  FROM_TIME: 'Booking from time',
  TO_TIME: 'Booking to time',
  YOU_HAVE_COMPLETED: 'You have Completed',
  PAYMENT_PENDING: 'PAYMENT_PENDING',
  PAYMENT_FAILED: 'PAYMENT_FAILED',
  PAYMENT_OPTION: 'Payment Pending',
  TRANSFER_FAILED: 'TRANSFER_FAILED',
  AMT_TRANSFER_FAILED: 'AMOUNT_TRANSFER_FAILED',
  AMT_TRANSFER_SUCCESS: 'AMOUNT_TRANSFER_SUCCESS',
  PAY_NOW: 'Pay Now',
  AMT_NOT_TRANSFERED_YET: 'Amount not transfered yet',
  AMT_NOT_TRANSFERED: 'Amount not transfered',
  SUBMIT_FEEDBACK: 'Submit your feedback',
  PAYMENT_COMPLETED: 'Payment completed successfully',
  BOOKING_COMPLETED: 'Booking completed successfully',
  NOTES: 'Notes',
  CHEF_BOOKING_NOTES: 'Chef booking notes',
  CUSTOMER_BOOKING_NOTES: 'Customer notes',
  BOOKING_PRICE: 'Booking Price',
  DISHES: 'Dishes Type',
  COMPLETED_ALERT: 'Are you sure you want to Complete?',
  ACCEPT_ALERT: 'Are you sure you want to accept this request?',
  REJECT_ALERT: 'Are you sure you want to reject this request?',
  CANCEL_ALERT: 'Are you sure you want to cancel this request?',
  NO: 'No',
  YES: 'Yes',
  STRIPEID_MISSING_MSG: 'Please add your card for payment updation!',
  COMPLETED_VALIDATION: `You can't complete booking before booking start date!`,
  BOOKING_SUMMARY: 'Booking Summary',
  BOOKING_DIETARY: 'Dietary Restrictions',
  BOOKING_UTENSILES: 'Kitchen Equipments',
  BOOKING_ALLERGY: 'Allergies',
  BOOKING_NO_OF_PEOPLE: 'No. of people',
  BOOKING_COMPLEXITY: 'Complexity',
  BOOKING_FOOD_COST: 'Food Cost',
  BOOKING_ADDITIONAL_SERVICE: 'Additional Service',
};
