/** @format */

export default {
  //sample
  SAMPLE_DATE: '6 September, Friday',
  SAMPLE_DURATION: 'From jan1 2019 till',
  SAMPLE_COMMISSIOM_EARNED: '400000 Lac',
  SAMPLE_FEEDBACK: `To solve this problem, we recommend asking customers to give you feedback on a
  specific aspect of your business when you ask for a review. If you’re a car
  dealership, you might ask about the cleanliness of the showroom or the length of
  the car-buying process. If you’re a home services business, you might ask about
  the friendliness or knowledge of your staff.`,

  //Screen names
  DASHBOARD: 'Dashboard',
  CUSTOMERMANAGEMENT: 'Customer Management',
  CHEFMANAGEMENT: 'Chef Management',
  BOOKINGHISTORY: 'Booking History',
  COMMISSIONMANAGEMENT: 'Commission Management',
  REVIEWSRATINGS: 'Reviews and Ratings',
  CUISINES_DISHES: 'Cuisines and Dishes',
  PROFILEMANAGEMENT: 'Profile Management',
  FEEDBACK: 'Feedback',
  SETTINGS: 'Settings',

  //Lables
  NO_DATA: 'No Data',
  REFER_DISH_TYPES: 'Refer Dish Types',
  REFER_CUISINE_TYPES: 'Refer Cuisine Types',
  CUISINES: 'Cuisines',
  DISHES: 'Dishes:',
  LOAD_MORE: 'Load More',
  SEARCH: 'Search',
  RESET: 'Reset',
  RATINGS: 'Ratings',
  STATUS_FILTER: 'Status Filter',
  SERIAL_NUMBER: 'S.NO',
  REVIEWER_NAME: 'Reviewer Name',
  ADD_CHEF: 'Add New Chef',
  ADD_CUSTOMER: 'Add New Customer',
  NEW_CHEFS: 'New Chefs',
  NO_NEW_CHEF: 'No new chefs',
  NO_NEW_CUSTOMER: 'No new customers',
  NEW_CUSTOMERS: 'New Customers',
  CHEF_TITLE: `All Chef's`,
  CUSTOMER_TITLE: 'All Customers',
  SHOW: 'Show: ',
  MONTH: 'Monthly',
  CUSTOM: 'Custom',
  WEEK: 'Weekly',
  YEAR: 'Yearly',
  BLOCK: 'Block',
  UNBLOCK: 'Unblock',
  APPROVE: 'Approve',
  SUBMITTED_FOR_REVIEW: 'Submitted for Review',
  REJECT: 'Reject',
  VIEW: 'View',
  PENDING: 'Pending',
  STATUS: 'Status',
  CUSTOMER_ID: 'Customer Id',
  NAME: 'Name',
  CHEF_NAME: 'Chef Name',
  CUSTOMER_NAME: 'Customer Name',
  CHEF: 'Chef',
  ADMIN: 'Admin',
  CUSTOMER: 'Customer',
  DATE: 'Date',
  TIME: 'Time',
  BLOCK_UNBLOCK: 'Block/Unblock',
  ACTION: 'Action',
  USER: 'Users',
  ACCEPT: 'Accept',
  CANCEL: 'Cancel',
  CHEF_ACCEPT: 'Chef accepted',
  CHEF_CANCEL: 'Chef cancelled',
  CUSTOMER_CANCEL: 'Customer cancelled',
  SHOW_MORE: 'Show more',
  REGISTER_DATE: 'Register Date:',
  BUSINESS_PROGRESS: 'Business Progress',
  BOOKING_HISTORY: 'Booking History',
  BOOKINGDETAILS: 'Booking Details',
  BOOKING_DESCRIPITION: 'Booking Descripition',
  PAYMENT_DETAILS: 'Payment Details',
  BOOKING_NOTES: 'Booking Notes',
  BOOKING_ADDRESS: 'Booking Address:',
  CHART_TYPE: 'line',
  AMOUNT: 'Amount',
  INR: 'INR ',
  COMMISSION_MANAGEMENT: 'Commission Management',
  COMMISSION: 'Commission',
  UPDATE: 'Update',
  UPDATE_COMMISSION: 'Update Commission',
  COMMISSION_EARNED: 'Total Commission Earned',
  REVIEW: 'Reviews',
  REVIEWS_RATINGS: 'Reviews and Ratings',
  PROFILE_TITLE: 'Profile Management',
  EMAIL_ID: 'Email Id',
  UPDATE_PASSWORD: 'Update Password',
  ALL: 'All',
  THIS_WEEK: 'This Week',
  THIS_MONTH: 'This Month',
  THIS_year: 'This Year',
  ADD: 'Add',
  CUSTOM_DATE: 'Custom',
  AWARDS: 'Awards',
  AWARDS_DES: 'Awards Descripition:',
  BACK: 'Back',
  PAYMENT: 'Payment',
  NAME_LABEL: 'Name:',
  EMAIL_LABEL: 'Email:',
  GENDER_LABEL: 'Gender:',
  REGISTERED_DATE_LABEL: 'Registered Date:',
  REGISTERED_DATE: 'Registered Date',
  REVIEWED_DATE: 'Reviewed Date',
  REVIEWED_BY: 'Reviewed By',
  REVIEWED_FOR: 'Reviewed For',
  AVERAGE_RATING_LABEL: 'Average Ratings:',
  PHONE_NUMBER_LABEL: 'Phone Number:',
  PHONE_NUMBER: 'Phone Number',
  CUISINE_TYPE_LABEL: 'Cuisine:',
  DISHES_SPECIALITY: 'Dish Specialty:',
  CERTIFICATION_LIST: 'Certification List',
  ALLERGY_LIST: 'Allergy List:',
  DIETARY_LIST: 'Dietary List:',
  KITCHEN_EQUIPMENT: 'Kitchen Equipment List:',
  EQUIPMENT: 'Kitchen Equipment:',
  FOOD_COST: 'Food Cost:',
  SERVICE_RATE: 'Service & Rate:',
  DISH_TYPE_LABEL: 'Dishes:',
  DESCRIPTION_LABEL: 'Description:',
  LOCATION_LABEL: 'Location:',
  BASE_RATE: 'Base Rate:',
  GRATUITY: 'Gratuity:',
  NO_OF_GUESTS: 'No of Guests:',
  NO_OF_PEOPLE: 'No of People:',
  PAYMENT_ID: 'Payment Id:',
  NO_OF_ITEMS: 'No of items:',
  ADDITIONAL_BASE_RATE: 'Each guest an additional X your base rate:',
  DISCOUNT_FOR_GUEST: 'Discount for each guest after',
  CHEF_TRAVEL: 'Chef can travel around',
  PROVIDE_SERVICE: 'to provide the service.',
  HOUR_LABEL: '/ hour',
  MIN: 'Min:',
  MAX: ' Max:',
  CHEF_COOK: 'Chef can cook',
  MEMBERS: 'members',
  FOR: 'for',
  PERSONS: 'Persons',
  REQUESTED_TIME_LABEL: 'Requested Time:',
  REQUESTED_DATE_LABEL: 'Requested Date:',
  BUSINESS_HOURS: 'Booking Hours:',
  CUSTOMER_REVIEW_LABLE: 'Customer Reviews and Ratings',
  CENCELLATION_REASON: 'Cancellation Reason',
  DOCUMENT_LABEL: 'Document',
  CHEF_REVIEW_LABLE: 'Chef Reviews and Ratings',
  FACEBOOK_LABEL: 'Facebook Url:',
  TWITER_LABEL: 'Twitter Url:',
  COST_UNIT_LABEL: 'Price Unit:',
  COST_LABEL: 'Price:',
  DRIVIG_LICENSE_LABEL: 'Driving License No:',
  REVIEW_LABEL: ' review',
  REVIEWS_LABEL: ' reviews',
  WORK_GALLERY_LABEL: 'Work Gallery',
  CONTACT_LABEL: 'Contact Details',
  PERSONAL_LABEL: 'Personal Details',
  SPECIALIZATION_LABEL: 'Specialization Details',
  ADDITIONAL_SERVICE: 'Additional Service & Price',
  ADDITIONAL: 'Additional Service:',
  ADDITIONAL_SER: 'Additional Service',
  COMPLEXITY_CHANGE: 'Complexity Changes:',
  TOTAL_AMOUNT_EXTRA: 'Total Amount for Extra Services:',
  REQUESTED_AMOUNT: 'Requested Amount:',
  CERTIFICATION_TYPE: 'Certification Types',
  ALLERGY_TYPE: 'Allergy Types',
  DIETARY_TYPE: 'Dietary Types',
  KITCHEN_TYPE: 'Kitchen Equipment Types',
  DOB_LABEL: 'DOB:',
  BUSINESS_LABEL: 'Business Details',
  COMPLEXITY: 'Complexity',
  COMPLEXITY_LEVEL: 'Complexity Level:',
  COMPLEXITY_CHARGE: 'Complexity Charge:',
  ADDITIONAL_NO_OF_PEOPLE: 'Additional No of People:',
  EXTRA_SERVICE_PROVIDER: 'Extra Service Provided:',
  CHEF_TOTAL_CHARGE: 'Chef Total Charge:',
  ROCKOLY_CHARGE: 'Rockoly Charge:',
  TOTAL_AMOUNT: 'Total Amount:',
  TOTAL_REMAINING_AMOUNT: 'Total Remaining Amount Paid:',
  PAYMENT_STATUS: 'Payment Status:',
  PAYMENT_DATE: 'Payment Date:',
  PAYMENT_PRICE: 'Payment Price:',
  BOOKING_STATUS: 'Booking Status:',
  BUSSINESS_TIME_LABEL: 'Business Time:',
  EXPERIANCE_LABEL: 'Experience:',
  SERVICE_COST: 'Service Cost',
  SERVICE_TIME: 'Service Time',
  SERVICE_DATE: 'Service Date',
  BOOKED_ON: 'Booked On',
  PERCENT: '%',
  REVIEW_DETAILS: 'Review Details',
  REVIEW_DONE_BY: 'Review Done By:',
  REVIEW_DONE_FOR: 'Review Done for:',
  REVIEW_RATING: 'Review Rating:',
  REVIEW_DESCRIPTION: 'Review Description:',
  REVIEW_ON: 'Reviewed On:',
  SEND_TO_CHEF: 'Send to Chef',
  RESET_PASSWORD: 'Reset Password',
  BOOKING_ID: 'Booking Id:',
  BOOKING_SUMMARY: 'Summary:',
  OTHERALLERGY: 'Other Allergies',
  OTHER_DIETARY: 'Other Dietaries',
  OTHER_KITCHEN_EQUIPMENTS: 'Other Kitchen Equipment',
  NO_REVIEWS: 'No Reviews Yet',
  SEND_MAIL: 'Send Mail',
  ENTER_SUBJECT: 'Enter the Subject',
  ENTER_CONTENT: 'Enter the Content',
  ENTER_REASON: 'Enter the Reason',
  TRACKORDERNO: 'trackOrderNo',
  ASC: 'asc',
  NOTES: 'Notes',
  PROFILE_NOT_SUBMITTED: 'Profile Not Submitted',
  CERTIFICATE: 'Certificate',
  LICENSE: 'License',
  OTHER_ATTACHMENT: 'Other Attachment',
  OKTEXT: 'Yes',
  CANCELTEXT: 'No',
  CANCELLATION_SETTINGS_LABEL: 'Cancellation Settings',
  STRIPE_CENTS: 'Stripe Cents Settings',
  UPDATE_STRIPE: 'Update Stripe Cents',
  STRIPE_CENTS_LABLE: 'Stripe Cents:',
  CANCELLATION_TIME_LABEL: 'Cancellation Time:',
  UPDATE_CANCELLATION_TIME: 'Update Cancellation Time In Hours',

  CHEF_AMOUNT_TRANSFER_FAILED: 'Chef Amount Transfer Failed',
  CHEF_REQUESTED_AMOUNT: 'Chef Rquested Amount',
  AMOUNT_TRANSFER_FAILED: 'Amount Transfer Failed',
  REVIEW_DONE_BY_CUSTOMER: 'Review Done By Customer',
  REVIEW_DONE_BY_CHEF: 'Review Done By Chef',
  CHEF_AMOUNT_TRANSFERRED_SUCCESS: 'Chef Amount Transferred Success',
  COMPLETED: 'Completed',
  PAYMENT_FAILED: 'Payment Failed',
  AMOUNT_TRANSFER_SUCCESS: 'Amount Transfer Success',
  PAYMENT_PENDING: 'Payment Pending',
  CUSTOMER_REQUESTED: 'Customer Requested',
  CHEF_ACCEPTED: 'Chef Accepted',
  CHEF_REJECTED: 'Chef Rejected',
  CANCELLED_BY_CHEF: 'Cancelled By Chef',
  CANCELLED_BY_CUSTOMER: 'Cancelled By Customer',
  COMPLETED_BY_CUSTOMER: 'Completed by Customer',
  COMPLETED_BY_CHEF: 'Completed by Chef',
  PAY_TO_CHEF: 'Pay to Chef',
  REFUND_TO_CUSTOMER: 'Refund to Customer',
  BOTH_CHEF_AND_CUSTOMER_COMPLETED: 'Both Chef and Customer Completed',
  CUSTOMER_CENCELLATION_REASON: 'Customer Cencellation reason',
  CHEF_CENCELLATION_REASON: 'Chef Cencellation or Rejection reason',
  CUSTOMER_REFUND_TRANSFERRED_SUCCESS: 'Customer Refund Transferred Success',
  CUSTOMER_REFUND_TRANSFER_FAILED: 'Customer Refund Transfer Failed',
  REFUND_AMOUNT_SUCCESS: 'Refund Amount Success',

  SINGLE_ACTION: 'Single action',
  BULCK_ACTION: 'Bulk action',

  //message:
  INVALIDE_COMMISSION: 'Please enter the commission',
  UPDATE_SUCCESSFULLY: 'Update successfully',

  //Component labels
  THEME: 'filled',
  DOWNICON: 'caret-down',
  ALTERNATE_PIC: 'profile',
  OKTEXT: 'Yes',
  CANCELTEXT: 'No',
  PLACEMENT_LEFT: 'left',
  PLACEMENT_BOTTOM: 'bottom',
  BUTTOM_RIGHT: 'bottomRight',
  VERTICAL: 'vertical',
  SEARCH: 'Search',

  //Icons
  EDIT_ICON: 'edit',
  DELETE_ICON: 'delete',
  CLOSE_CIRCLE_ICON: 'close-circle',
  CHECK_CIRCLE_ICON: 'check-circle',
  CLOCK_CIRCLE_ICON: 'clock-circle',

  //Messages
  APPROVED: 'Approved',
  REJECTED: 'Rejected',
  BLOCKED: 'Blocked',
  UNBLOCKED: 'Unblocked',
  REVIEWED: 'Reviewed',
  NO_MAIL: 'No mail id',
  SENT_MAIL_SUCCESS: 'Mail sent successfully',
  ERROR_CONTENT: 'Please enter the contant',
  ERROR_SUBJECT: 'Please enter the subject',
  ERROR_SUBJECT_ERROR_CONTENT: 'Please enter the subject and content',
  ERROR_SELECT_REVIEWS: 'Please select the reviews',
  SEARCH_ERROR: 'Please enter atleast three characters',
  ENTER_NOTES: 'Please enter notes.',
  CHEF_BANK_ACCOUNT: 'Pelase, Ask Chef to add bank account to transfer the payment',
  WENT_WRONG: 'Something went wrong. Please try again later.',
  CANCELLATION_TIME_ERROR: 'Please enter the cancellation time.',
  UPDATE_STRIPE_ERROR: 'Please enter the stripe cents.',
  REJECT_CUISINE_ALERT: 'Are you sure. You want to reject this cuisine.',
  REJECT_DISH_ALERT: 'Are you sure. You want to reject this dish.',

  //PopConfirm customer
  CUSTOMER_DELETE_ALERT: 'Are you sure. You want to delete this customer.',
  CUSTOMER_EDIT_ALERT: 'Are you sure. You want to edit this customer.',
  CUSTOMER_SELECTED_BLOCK_ALERT: 'Are you sure. You want to block the selected customers.',
  CUSTOMER_BLOCK_ALERT: 'Are you sure. You want to block this customer.',
  CUSTOMER_REJECT_ALERT: 'Are you sure. You want to reject this customer.',
  CUSTOMER_SELECT_BLOCK: 'Please select the customer. You want to block',
  CUSTOMER_SELECT_UNBLOCK: 'Please select the customer. You want to unblock',
  SELECT_CUSTOMER: 'Please select the customer',
  ERROR_ENTER_REASON: 'Please enter the reason',

  //Popconfirm chef
  CHEF_DELETE_ALERT: 'Are you sure. You want to delete this chef.',
  CHEF_EDIT_ALERT: 'Are you sure. You want to edit this chef.',
  CHEF_SELECTED_BLOCK_ALERT: 'Are you sure. You want to block the selected chefs.',
  CHEF_BLOCK_ALERT: 'Are you sure. You want to block this chefs.',
  CHEF_REJECT_ALERT: 'Are you sure. You want to reject this chefs.',
  CHEF_SELECT_BLOCK: 'Please select the chef. You want to block',
  CHEF_SELECT_UNBLOCK: 'Please select the chef. You want to unblock',

  //Popconfirm review
  REVIEW_SELECTED_BLOCK_ALERT: 'Are you sure. You want to block the selected reviews.',
  REVIEW_SELECTED_EDIT_ALERT: 'Are you sure. You want to edit the selected users.',
  REVIEW_SELECTED_DELETE_ALERT: 'Are you sure. You want to delete the selected users.',
}
