/** @format */

export default {
  approveBotton: {
    color: '#35CA45',
    width: 80,
    borderColor: '#35CA45',
    borderWidth: 1,
    fontWeight: 600,
    height: 27,
  },
  viewBotton: {
    color: '#1077EA',
    width: 80,
    borderColor: '#1077EA',
    borderWidth: 1,
    fontWeight: 600,
    height: 27,
  },
  statusFilter: {
    width: 200,
    marginLeft: 20,
    marginTop: -2,
  },
  viewEyeBotton: {
    color: '#1077EA',
    cursor: 'pointer',
    fontSize: 20,
    marginRight: 20,
  },
  rejectBotton: {
    marginLeft: 5,
    width: 80,
    color: '#F24635',
    borderColor: '#F24635',
    borderWidth: 1,
    fontWeight: 600,
    height: 27,
  },
  imageStyle: {
    display: 'flex',
    width: 30,
    height: 30,
    borderRadius: '50%',
  },
  nameField: {
    display: 'flex',
    flexDirection: 'row',
  },
  nameStyle: {
    fontWeight: 600,
    fontSize: 15,
    color: 'black',
    textTransform: 'capitalize',
  },
  reviewerNameStyle: {
    fontWeight: 600,
    fontSize: 15,
    color: 'black',
    textTransform: 'capitalize',
    marginLeft: 10,
  },
  emailtableStyle: {
    marginTop: -15,
  },
  profileContentView: {
    marginLeft: 10,
  },
  nameLinkStyle: {
    fontWeight: 600,
    fontSize: 15,
    color: 'black',
    textTransform: 'capitalize',
    marginLeft: 10,
    textDecoration: 'underLine',
    cursor: 'pointer',
  },
  titleTextStyle: {
    fontWeight: 'bold',
    fontSize: 15,
    color: 'black',
    textTransform: 'capitalize',
    marginLeft: 10,
  },
  top_titleTextStyle: {
    fontWeight: 'bold',
    fontSize: 15,
    color: 'black',
    textTransform: 'capitalize',
    marginLeft: 10,
    marginTop: 10,
  },
  emptyText: {
    fontWeight: 'bold',
    textAlign: 'center',
    fontSize: 15,
    color: 'black',
    textTransform: 'capitalize',
    marginLeft: 10,
    marginTop: 10,
  },
  grayText: {
    fontWeight: 400,
    fontSize: 15,
    color: 'black',
  },
  reviewDecText: {
    fontWeight: 400,
    fontSize: 15,
    color: 'black',
    width: 150,
  },
  addButtonStyle: {
    backgroundColor: '#515151',
    color: 'white',
    marginLeft: 50,
    height: 23,
  },
  upperView: {
    display: 'flex',
    justifyContent: 'space-between',
    flexDirection: 'row',
    backgroundColor: 'white',
    border: '1px solid #E4E4E4',
    width: '100%',
    marginLeft: 0,
    marginTop: 10,
    height: 'auto',
  },
  subView: {
    display: 'flex',
    marginTop: 10,
    width: 450,
    justifyContent: 'space-evenly',
  },
  chefsubView: {
    display: 'flex',
    marginTop: 10,
    width: 400,
    justifyContent: 'flex-end',
  },
  firstSubView: {
    display: 'flex',
    marginTop: 10,
  },
  monthFilterView: {
    marginRight: 5,
  },
  top_monthFilterView: {
    marginRight: 10,
    marginTop: 10,
  },
  editIconStyle: {
    fontSize: 15,
    color: '#A9A5A4',
    marginTop: 5,
  },
  deleteIconStyle: {
    fontSize: 15,
    color: '#A9A5A4',
    marginTop: 5,
  },
  monthText: {
    marginLeft: 5,
    color: '#33CAFF',
    fontWeight: 600,
    cursor: 'pointer',
  },
  showText: {
    fontWeight: 600,
  },
  downIcon: {
    marginTop: 5,
    marginLeft: 5,
    cursor: 'pointer',
  },
  approvalStyle: {
    fontWeight: 600,
    fontSize: 15,
    marginLeft: 50,
  },
  actionStatus: {
    fontWeight: 600,
    fontSize: 15,
    textAlign: 'center',
  },
  statusTextStyle: {
    fontWeight: 600,
    fontSize: 15,
  },
  nameHeader: {
    marginLeft: 25,
  },
  actionHeader: {
    marginLeft: 60,
  },
  lowerViewTittleFilter: {
    marginTop: 10,
    display: 'flex',
    justifyContent: 'space-between',
    flexDirection: 'row',
    backgroundColor: 'white',
    width: '97%',
    marginLeft: 10,
  },
  loaderStyle: {
    marginTop: 20,
    display: 'flex',
    justifyContent: 'center',
  },
  actionButtonView: {
    width: 200,
  },
  alignActionButtons: {
    display: 'flex',
    justifyContent: 'center',
  },
  alignPaginationComponents: {
    display: 'flex',
    flexdirect: 'row',
    margin: 10,
    justifyContent: 'flex-end',
  },
  modalButtonView: {
    display: 'flex',
    justifyContent: 'flex-end',
    marginTop: 10,
  },
  loadMoreStyle: {
    marginRight: 10,
  },
  loadMoreView: {
    display: 'flex',
    justifyContent: 'flex-end',
    marginTop: -10,
    // marginBottom: 10,
  },
}
