/** @format */

export const DATA = {
  sampleData: [
    {
      customerId: '#112211',
      name: 'Victor Simth',
      date: '12July, 2019',
      blockStatus: false,
      approvalStatus: null,
      role: 'Customer',
      amount: 2000,
      reason: 'Refund',
      review: 'Good work',
      email: 'Victor@gmail.com',
      profilePic:
        'https://firebasestorage.googleapis.com/v0/b/tourzey-dev.appspot.com/o/tour%2Fimage.jpg_1560268645107?alt=media&token=9fca6d4a-7338-4965-ab2e-3ce630b8ce38',
    },
    {
      customerId: '#112222',
      name: 'Babu sam',
      date: '12July, 2019',
      blockStatus: true,
      approvalStatus: 'Approved',
      role: 'Chef',
      amount: 2000,
      reason: 'Refund',
      review: 'He gives of himself to make sure the job is well done.',
      email: 'babu@gmail.com',
      profilePic:
        'https://firebasestorage.googleapis.com/v0/b/tourzey-dev.appspot.com/o/profile%2Fimage.jpg_1560418342420?alt=media&token=a5bcf790-e17a-454e-8d2a-7b334ac0d6eb',
    },
    {
      customerId: '#112233',
      name: 'Velu',
      date: '12July, 2019',
      blockStatus: false,
      approvalStatus: null,
      role: 'Customer',
      amount: 2000,
      reason: 'Refund',
      review: 'He accepts constructive criticism positively.',
      email: 'velu@gmail.com',
      profilePic:
        'https://firebasestorage.googleapis.com/v0/b/tourzey-dev.appspot.com/o/tour%2Fimage.jpg_1560268645107?alt=media&token=9fca6d4a-7338-4965-ab2e-3ce630b8ce38',
    },
    {
      customerId: '#112244',
      name: 'siva',
      date: '12July, 2019',
      blockStatus: false,
      approvalStatus: null,
      role: 'Chef',
      amount: 2000,
      reason: 'Refund',
      review: 'Taste are so good and smart work',
      email: 'siva@gmail.com',
      profilePic:
        'https://firebasestorage.googleapis.com/v0/b/tourzey-dev.appspot.com/o/profile%2Fimage.jpg_1560418342420?alt=media&token=a5bcf790-e17a-454e-8d2a-7b334ac0d6eb',
    },
    {
      customerId: '#112255',
      name: 'shankar',
      date: '12July, 2019',
      blockStatus: true,
      approvalStatus: null,
      role: 'Chef',
      amount: 2000,
      reason: 'Refund',
      review: 'I am satisfied with his work',
      email: 'shankar@gmail.com',
      profilePic:
        'https://firebasestorage.googleapis.com/v0/b/tourzey-dev.appspot.com/o/tour%2Fimage.jpg_1560268645107?alt=media&token=9fca6d4a-7338-4965-ab2e-3ce630b8ce38',
    },
    {
      customerId: '#112266',
      name: 'sharma',
      date: '12July, 2019',
      blockStatus: false,
      approvalStatus: 'Rejected',
      role: 'Customer',
      amount: 2000,
      reason: 'Refund',
      review: 'He took more time for preparation. guests are waiting for few hours',
      email: 'sharma@gmail.com',
      profilePic:
        'https://firebasestorage.googleapis.com/v0/b/tourzey-dev.appspot.com/o/profile%2Fimage.jpg_1560418342420?alt=media&token=a5bcf790-e17a-454e-8d2a-7b334ac0d6eb',
    },
    {
      customerId: '#112277',
      name: 'mohamath',
      date: '12July, 2019',
      blockStatus: false,
      approvalStatus: 'Rejected',
      role: 'Chef',
      amount: 2000,
      reason: 'Refund',
      review: 'Thank you',
      email: 'mohamath@gmail.com',
      profilePic:
        'https://firebasestorage.googleapis.com/v0/b/tourzey-dev.appspot.com/o/profile%2Fimage.jpg_1560418342420?alt=media&token=a5bcf790-e17a-454e-8d2a-7b334ac0d6eb',
    },
    {
      customerId: '#112288',
      name: 'durai',
      date: '12July, 2019',
      profilePic: null,
      blockStatus: false,
      approvalStatus: null,
      role: 'Customer',
      amount: 2000,
      reason: 'Refund',
      review: 'I will refer to others',
      email: 'durai@gmail.com',
    },
    {
      customerId: '#112299',
      name: 'dharsah',
      date: '12July, 2019',
      profilePic: null,
      blockStatus: false,
      approvalStatus: null,
      role: 'Customer',
      amount: 2000,
      reason: 'Refund',
      review: 'Really good',
      email: 'dharsah@gmail.com',
    },
    {
      customerId: '#112200',
      name: 'mugin',
      date: '12July, 2019',
      profilePic: null,
      blockStatus: false,
      approvalStatus: null,
      role: 'Customer',
      amount: 2000,
      reason: 'Refund',
      review: 'Worst',
      email: 'mugin@gmail.com',
    },
    {
      customerId: '#111133',
      name: 'sandy',
      date: '12July, 2019',
      profilePic: null,
      blockStatus: false,
      approvalStatus: null,
      role: 'Customer',
      amount: 2000,
      reason: 'Refund',
      review: 'Unsatisfied',
      email: 'sandy@gmail.com',
    },
    {
      customerId: '#114433',
      name: 'kavin',
      date: '12July, 2019',
      blockStatus: false,
      approvalStatus: null,
      role: 'Customer',
      amount: 2000,
      reason: 'Refund',
      review: 'Unbelievable work',
      email: 'kavin@gmail.com',
      profilePic:
        'https://firebasestorage.googleapis.com/v0/b/tourzey-dev.appspot.com/o/profile%2Fimage.jpg_1560418342420?alt=media&token=a5bcf790-e17a-454e-8d2a-7b334ac0d6eb',
    },
    {
      customerId: '#115533',
      name: 'william',
      date: '12July, 2019',
      blockStatus: false,
      approvalStatus: null,
      role: 'Customer',
      amount: 2000,
      reason: 'Refund',
      review: 'Good work',
      email: 'william@gmail.com',
      profilePic:
        'https://firebasestorage.googleapis.com/v0/b/tourzey-dev.appspot.com/o/tour%2Fimage.jpg_1560268645107?alt=media&token=9fca6d4a-7338-4965-ab2e-3ce630b8ce38',
    },
    {
      customerId: '#116633',
      name: 'smith',
      date: '12July, 2019',
      blockStatus: false,
      approvalStatus: null,
      role: 'Customer',
      amount: 2000,
      reason: 'Refund',
      review: 'Good work',
      email: 'smith@gmail.com',
      profilePic:
        'https://firebasestorage.googleapis.com/v0/b/tourzey-dev.appspot.com/o/tour%2Fimage.jpg_1560268645107?alt=media&token=9fca6d4a-7338-4965-ab2e-3ce630b8ce38',
    },
  ],
  graphData: {
    options: {
      chart: {
        id: 'basic-bar',
      },
      xaxis: {
        categories: ['Sep1', 'Sep8', 'Sep17', 'Sep24', 'Sep30'],
      },
    },
    series: [
      {
        name: 'series-1',
        data: [30, 40, 45, 50, 49],
      },
    ],
  },
  commissionData: [
    {updatedDate: '01 September 2019', commission: '1%'},
    {updatedDate: '09 June 2019', commission: '2%'},
  ],
}
