/** @format */

import {Dimensions, Platform} from 'react-native'
import {Color} from '@common'
import {Theme} from '@theme'

export const SCREEN_WIDTH = Dimensions.get('window').width
export const SCREEN_HEIGHT = Dimensions.get('window').height
const {width} = Dimensions.get('window')
const vw = width / 100
export default {
  mainView: {
    flex: 1,
  },
  container: {
    marginHorizontal: 10,
    marginVertical: 10,
  },
  body2: {
    color: 'gray',
    fontSize: 30,
    marginTop: 30,
  },
  chefImage: {
    alignItems: 'center',
    justifyContent: 'center',
    height: 100,
    width: 100,
    borderRadius: 50,
  },
  galleryImage: {
    marginLeft: vw * 2,
    marginRight: vw * 2,
    marginTop: 12,
    marginBottom: 8,
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
    width: '25%',
    height: vw * 25,
    borderRadius: 50,
  },
  iconStyle: {
    fontSize: 100,
    color: Theme.Colors.primary,
  },
  profileHeader: {
    flexDirection: 'row',
  },
  userName: {
    marginTop: 20,
    marginLeft: 30,
    fontWeight: 'bold',
    fontSize: 24,
    color: 'black',
  },
  iconBody: {
    display: 'flex',
    flexDirection: 'row',
  },
  // cusineBody: {
  //   display: 'flex',
  //   flexDirection: 'row',
  //   flexWrap: 'wrap',
  //   marginTop: 15,
  //   marginLeft: 10,
  // },
  // chipItem: {
  //   marginHorizontal: 5,
  //   marginVertical: 5,
  //   backgroundColor: 'white',
  //   borderColor: 'grey',
  //   borderWidth: 1,
  // },
  iconProfileBody: {
    display: 'flex',
    flexDirection: 'row',
    flex: 1,
    justifyContent: 'space-between',
    width: '100%',
  },
  iconNameView: {
    display: 'flex',
    flexDirection: 'row',
    flex: 1,
    justifyContent: 'space-between',
  },
  iconNameView2: {
    display: 'flex',
    flexDirection: 'row',
    flex: 1,
    marginTop: 5,
  },

  dateSelection: {
    height: 50,
    display: 'flex',
    flexDirection: 'row',
    backgroundColor: Theme.Colors.primary,
    borderRadius: 15,
    marginTop: 5,
  },
  iconText: {
    display: 'flex',
    flexDirection: 'column',
    width: '100%',
    flex: 1,
  },
  text: {
    color: 'black',
    fontSize: 18,
    fontWeight: 'bold',
    width: '70%',
    textTransform: 'capitalize',
    flexWrap: 'wrap',
    marginLeft: 5,
  },
  text2: {
    color: 'gray',
    fontSize: 14,
    marginLeft: 5,
    width: '80%',
  },
  text3: {
    color: Theme.Colors.primary,
    fontSize: 12,
    marginLeft: 5,
    fontWeight: 'bold',
    marginTop: 15,
  },
  text4: {
    fontSize: 12,
    marginLeft: 5,
    marginTop: 15,
  },
  iconStyle2: {
    fontSize: 15,
    marginLeft: 5,
    color: Theme.Colors.primary,
  },
  iconStyle3: {
    fontSize: 30,
    color: Theme.Colors.primary,
    marginLeft: '5%',
  },
  iconStyle4: {
    fontSize: 20,
    color: Theme.Colors.primary,
    marginTop: 15,
    marginLeft: 25,
  },
  calenderStyle: {
    fontSize: 25,
    marginTop: 15,
    marginLeft: 25,
  },
  iconStyle5: {
    fontSize: 20,
    color: 'gray',
    marginTop: 15,
    marginLeft: 25,
  },
  calenderIcon: {
    fontSize: 20,
    color: 'white',
    marginTop: 17,
    marginLeft: 25,
  },
  angleStyle: {
    fontSize: 20,
    color: 'white',
    marginTop: 15,
    marginLeft: 60,
    alignSelf: 'right',
  },
  starSpacing: {
    marginTop: 15,
  },
  displayStar: {
    marginTop: 15,
  },
  iconBody2: {
    display: 'flex',
    flexDirection: 'row',
    // marginBottom:,
  },
  border: {
    borderBottomColor: '#B9BFBB',
    borderBottomWidth: 1,
    marginTop: 10,
    marginLeft: 10,
    marginRight: 10,
  },
  ratingBorder: {
    borderBottomColor: '#646262',
    borderBottomWidth: 1,
    // marginTop: 5,
    // marginLeft: 5,
    // marginRight: 5,
  },
  lowerText: {
    color: Theme.Colors.primary,
    fontWeight: Platform.OS === 'ios' ? 600 : 'lighter',
    fontSize: 14,
    marginLeft: 15,
    marginTop: 15,
  },
  lowerText2: {
    color: Theme.Colors.primary,
    fontSize: 14,
    marginLeft: 15,
    fontWeight: 'bold',
    marginTop: 15,
  },
  heading: {
    color: 'black',
    fontSize: 16,
    marginTop: 20,
    paddingLeft: 10,
  },
  discount: {
    color: 'black',
    width: '65%',
    fontSize: 16,
    marginTop: 20,
    paddingLeft: 10,
  },
  destext: {
    color: 'black', // B9BFBB
    fontSize: 14,
    marginTop: 15,
    paddingLeft: 20,
  },
  biilingRightText: {
    color: 'black',
    fontSize: 14,
    marginTop: 20,
    paddingLeft: 20,
    position: 'absolute',
    right: 5,
  },
  noteText: {
    color: 'black',
    fontSize: 14,
    paddingLeft: 10,
  },
  ratingText: {
    color: '#B9BFBB',
    fontSize: 14,
    marginTop: 10,
  },
  ratingFromText: {
    color: '#B9BFBB',
    fontSize: 14,
    marginTop: 10,
    marginBottom: 10,
  },

  // locationText: {
  //   color: Theme.Colors.primary,
  //   fontSize: 16,
  //   textAlign: 'center',
  //   alignItems: 'center',
  // },
  Caltext: {
    color: 'white',
    marginLeft: 30,
    fontSize: 18,
    marginTop: 15,
  },
  imageIcon: {
    display: 'flex',
    flexDirection: 'row',
    flex: 1,
    justifyContent: 'flex-start',
  },
  imageIconStyle2: {
    fontSize: 80,
    color: Theme.Colors.primary,
    marginLeft: 10,
  },
  rejectButton: {
    backgroundColor: '#FC7079',
    width: '45%',
    marginTop: 20,
    borderRadius: 30,
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
    elevation: 1,
    marginLeft: 10,
  },
  loginButton: {
    backgroundColor: Theme.Colors.primary,
    width: '45%',
    marginTop: 20,
    borderRadius: 30,
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
    elevation: 1,
  },
  payButton: {
    backgroundColor: Theme.Colors.primary,
    width: '55%',
    marginTop: 20,
    borderRadius: 30,
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
    elevation: 1,
  },
  bookingStatusBtn: {
    flexDirection: 'row',
    flex: 1,
    justifyContent: 'space-evenly',
    alignSelf: 'center',
    marginVertical: 10,
  },
  iconColor: {
    color: Theme.Colors.primary,
  },
  successBtn: {
    width: 55,
    height: 35,
    backgroundColor: Theme.Colors.primary,
    borderColor: Theme.Colors.primary,
    marginVertical: 5,
  },
  cancelBtn: {
    width: 55,
    height: 35,
    backgroundColor: Theme.Colors.error,
    borderColor: Theme.Colors.error,
    marginVertical: 5,
  },
  editBtn: {
    width: 55,
    height: 35,
    backgroundColor: Theme.Colors.accent,
    borderColor: Theme.Colors.accent,
    alignSelf: 'center',
    marginVertical: 5,
  },
  modelView: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'column',
    position: 'absolute',
    // paddingTop: '28%', // 83
    // paddingRight: 15,
    top: 0,
    bottom: 0,
    left: 0,
    right: 0,
    borderWidth: 1,
    borderColor: Theme.Colors.lightgrey,
    // backgroundColor: 'rgba(163,175,183, 0.5)',
    // backgroundColor: 'rgba(0,0,0, 0.2)',
    backgroundColor: 'rgba(0,0,0, 0.1)',
  },
  completeModelContainer: {
    backgroundColor: 'white',
    padding: 20,
    borderRadius: 10,
    marginHorizontal: 15,
    display: 'flex',
    flexDirection: 'column',
  },
  contentTextStyle: {
    textAlign: 'center',
    fontSize: 16,
    fontWeight: 'bold',
    color: 'black',
    marginVertical: 5,
  },
  btnView: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  primaryBtn: {
    backgroundColor: Theme.Colors.primary,
    marginTop: 5,
    // borderRadius: 30,
    // justifyContent: 'center',
    // alignItems: 'center',
    // alignSelf: 'center',
    // elevation: 1,
    minHeight: 20,
    padding: 3,
    borderRadius: 0,
    flexDirection: 'row',
  },
  dishItem: {
    paddingHorizontal: 10,
    marginHorizontal: 5,
    marginVertical: 5,
    backgroundColor: 'white',
    borderColor: 'grey',
    borderWidth: 1,
  },
  dishText: {
    color: Theme.Colors.primary,
    fontSize: 16,
    textAlign: 'center',
    alignItems: 'center',
    paddingHorizontal: 5,
  },
  dishView: {
    display: 'flex',
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginTop: 10,
    marginHorizontal: 5,
  },
  desView: {
    marginVertical: 5,
    marginHorizontal: 10,
  },
  cusineBody: {
    display: 'flex',
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginVertical: 10,
  },
  chipItem: {
    padding: 0,
    marginHorizontal: 5,
    marginVertical: 5,
    backgroundColor: 'white',
    borderColor: 'grey',
    borderWidth: 1,
  },
  locationText: {
    color: Theme.Colors.primary,
    fontSize: 14,
    textAlign: 'center',
    alignItems: 'center',
  },
  noTextStyle: {
    marginHorizontal: 10,
    color: '#B9BFBB',
    fontSize: 14,
  },
  cardStyle: {
    paddingHorizontal: 1,
    paddingVertical: 5,
    marginTop: 10,
    borderRadius: 10,
    marginHorizontal: 10,
  },
  reviewView: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'flex-start',
    marginVertical: 10,
  },
  avgNumber: {
    marginLeft: '1%',
    color: Theme.Colors.primary,
    fontWeight: 'bold',
  },
}
