export default {
  DESCRIPTION: 'Description',
  EXPERIENCE: 'Experience - year(s)',
  PRICE: 'Price per hour :',
  FACEBOOK_URL: 'Facebook URL',
  TWITTER_URL: 'Twitter URL :',
  LICENCE_NUMBER: 'Driving lincense number',
  LIST_BY_LOCATION: 'List by Location',
  SORT_BY_DATE: 'Sort by Date',
  NUMBER_OF_GUESTS: 'Number of Guests',
  HIGH_TO_LOW: 'High to Low',
  LOW_TO_HIGH: 'Low to High',
  TIME_OF_DAY: 'Time of Day',
  SUCCESS_MSG: 'Saved Successfully',
  UPDATE_MSG: 'Updated Successfully',
  SAVE: 'Save',
  SPECIALIZATION: 'Specialization',
  CUISINE: 'Cuisine',
  DISHES: 'Dishes',
  DISH_SPECIALTY: 'Dish Specialty',
  INGREDIENTS: 'Ingredients',
  GOOGLEAPI: 'https://maps.googleapis.com/maps/api/geocode/json?latlng=',
  KEY: '&key=',
  TEXT: 'text',
  NUMBER: 'number',
  EDIT_LOCATION_INFORMATION: 'Location',
  LOCATION: 'Location',
  ENTER_FULL_ADDRESS: 'Enter Full address',
  ADDRESS: 'address',
  ENTER_APARTMENT_NAME: 'Enter Apartment name',
  STREET_ADDRESS: 'streetAddress',
  PLEASE_ENTER_APARTMENT_NAME: 'Please enter Apartment name',
  ENTER_HOUSE_NO: 'Enter House No.',
  PLEASE_ENTER_HOUSE_NO: 'Please enter House No.',
  HOUSE_NO: 'houseNo',
  ENTER_ZIPCODE: 'Enter Zipcode',
  PLEASE_ENTER_ZIPCODE: 'Please enter Zipcode',
  ZIPCODE: 'zipcode',
  ENTER_DISTANCE: 'How much distance can you travel to provide service?(KM)',
  PLEASE_ENTER_DISTANCE: 'Please enter distance',
  DISTANCE: 'distance',
  CHEF_EDIT_PROFILE: 'chefEditProfile',
  CHEF_DETAIL: 'chefDetail',
  SUBMIT: 'Submit for Review',
  PENDING: 'PENDING',
  REJECTED: 'REJECTED',
  APPROVED: 'APPROVED',
  SUBMITTED_FOR_REVIEW: 'SUBMITTED_FOR_REVIEW',
  DATE_AVAILABLE: 'Please select a future date',
  TIME_AVAILABLE: 'Please select a future time',
  DATE_NOT_AVAILABLE: 'Please select chef available date and time',
  SET_UNAVAIALABILITY: 'Set Unavailability',
  ADD_UNAVAILABLE_DATE: 'Add Unavailable Date',
  REMOVE_DATE: 'Remove Unavailable Dates',
  // MINIMUN_HOUR_BOOKING: 'Minimum hour booking',
  MINIMUM_HOUR_ALERT: 'So, Please select availability hours according with minimum booking hours',
  MINIMUM_HOUR: 'Minimum booking',
  HOUR: 'hour.',
  HOURS: 'hours.',
  MINIMUN_HOUR_BOOKING: 'Minimum number of hours customer can book',
  SUBMIT_FOR_REVIEW_MSG:
    'Thank you for submitting profile with us, admin will verify and approve your account within 48 hours.',
  REVIEW_PENDING_MSG:
    'Please complete the below setup and submit your profile for review.  Once admin approval is received it will be available for customer selection.',
  REVIEW_REJECTED_MSG: 'Sorry, Your profile is rejected',
  PROFILE_VERIFIED_MSG: 'Your profile has been verified',
  SUBMIT_FOR_REVIEW: 'Submitted for review',
  REVIEW_PENDING: ' Pending',
  REVIEW_REJECTED: ' Rejected',
  PROFILE_VERIFIED: ' Verified',
  PROFILE_STATUS: `Your profile status: `,
  REASON: 'Reason: ',
  PREFERENCES: 'Preferences',
  ALLERGIES: 'If applicable, please list additional allergy.',
  DIETARY_RESTRICTIONS: 'If applicable, please list additional dietary restrictions.',
  ADDITIONAL_DIET: 'Please specify new dietary restriction(s) if applicable.',
  KITCHEN_UTENSILS: 'If applicable, please list any additional kitchen utensils. ',
  ADDITIONAL_UTENSILS: 'Please specify any additional equipment if applicable.',
  FAVORITE_CUISINE: 'Favorite Cuisines',
  VERIFIED_ALERT: 'Please verify email address and mobile number',
  SUBMIT_PROFILE: 'Submit',
};
