export default {
  ALL: 'All',
  CUSTOMER_REQUESTED: 'CUSTOMER_REQUESTED',
  CHEF_ACCEPTED: 'CHEF_ACCEPTED',
  CHEF_REJECTED: 'CHEF_REJECTED',
  CANCELLED_BY_CHEF: 'CANCELLED_BY_CHEF',
  CANCELLED_BY_CHEF_OR_CHEF_REJECTED: 'CANCELLED_BY_CHEF/CHEF_REJECTED',
  CANCELLED_BY_CUSTOMER: 'CANCELLED_BY_CUSTOMER',
  YOU_HAVE_COMPLETED: 'You have Completed',
  COMPLETED: 'COMPLETED',
  Complete: 'Complete',
  Completed: 'Completed',
  UPCOMING: 'Upcoming',
  CANCEL: 'Cancel',
  ACCEPT: 'Accept',
  Reject: 'Reject',
  TAB1: 'tab1',
  TAB2: 'tab2',
  TAB3: 'tab3',
  TAB4: 'tab4',
  TAB5: 'tab5',
  NO_DATA_AVAILABLE: 'No data Available',
  defaultImage: require('../../images/mock-image/default_chef_profile.png'),
  FROM_TIME: 'From Time: ',
  TO_TIME: 'To Time: ',
  CANCELLED_BY_CHEF_OR_CHEF_REJECTED_TEXT: 'You have Cancelled Booking / You have Rejected Booking',
  CANCELLED_BY_CUSTOMER_TEXT: 'Cancelled by Customer',
  CANCELLED_BY_CUSTOMER_TEXT1: 'You have Cancelled Booking',
  AWAITING_FOR_CHEF: 'Awaiting For Chef',
  TRANSFER_FAILED: 'TRANSFER_FAILED',
  AMT_TRANSFER_FAILED: 'AMOUNT_TRANSFER_FAILED',
  AMT_TRANSFER_SUCCESS: 'AMOUNT_TRANSFER_SUCCESS',
  PAYMENT_PENDING: 'PAYMENT_PENDING',
  PAYMENT_FAILED: 'PAYMENT_FAILED',
  AMT_NOT_TRANSFERED_YET: 'Amount not transfered yet',
  AMT_NOT_TRANSFERED: 'Amount not transfered',
  COMPLETED_ALERT: 'Are you sure you want to Complete?',
  ACCEPT_ALERT: 'Are you sure you want to accept this request?',
  REJECT_ALERT: 'Are you sure you want to reject this request?',
  CANCEL_ALERT: 'Are you sure you want to cancel this request?',
  NO: 'No',
  YES: 'Yes',
  STRIPEID_MISSING_MSG: 'Please add your card for payment updation!',
  COMPLETED_VALIDATION: `You can't complete booking before booking start date!`,
  BOOKING_COMPLETED: 'Booking completed successfully',
};
