/** @format */

export default {
  ROLE_CHOOSE: 'ROLE_CHOOSE',
  INTRO_SCREEN: 'INTRO_SCREEN',
  // switch
  CUSTOMER_SWITCH: 'CUSTOMER_SWITCH',
  CHEF_SWITCH: 'CHEF_SWITCH',
  AUTH_SWITCH: 'AUTH_SWITCH',
  // switch
  // main stack
  CUSTOMER_MAIN_STACK: 'CUSTOMER_MAIN_STACK',
  CHEF_MAIN_STACK: 'CHEF_MAIN_STACK',
  CUSTOMER_MAIN_TAB: 'CUSTOMER_MAIN_TAB',
  CHEF_MAIN_TAB: 'CHEF_MAIN_TAB',
  AUTH_STACK: 'AUTH_STACK',
  COMMON_STACK: 'COMMON_STACK',
  // main stack

  // customer tab stack
  FIND_CHEF_STACK: 'FIND_CHEF_STACK',
  FAVOURITE_STACK: 'FAVOURITE_STACK',
  BOOKING_HISTORY_STACK: 'BOOKING_HISTORY_STACK',
  CUSTOMER_PROFILE_STACK: 'CUSTOMER_PROFILE_STACK',
  // customer tab stack

  // chef tab stack
  HOME_STACK: 'HOME_STACK',
  BOOKING_REQUEST_STACK: 'BOOKING_REQUEST_STACK',
  PAYMENTS_STACK: 'PAYMENTS_STACK',
  CHEF_PROFILE_STACK: 'CHEF_PROFILE_STACK',
  CHEF_SETTING_STACK: 'CHEF_SETTING_STACK',
  CHEF_PAYMENT_HISTORY: 'CHEF_PAYMENT_HISTORY',
  // chef tab stack

  // auth
  LOGIN_SCREEN: 'LOGIN_SCREEN',
  REGISTER_SCREEN: 'REGISTER_SCREEN',
  PRE_REGISTER_SCREEN: 'PRE_REGISTER_SCREEN',
  COUSTUMER_REG_PROFILE: 'COUSTUMER_REG_PROFILE',
  CHEF_REG_PROFILE: 'CHEF_REG_PROFILE',
  FORGOT_PASSWORD_SCREEN: 'FORGOT_PASSWORD_SCREEN',
  OTP_VERIFICATION_SCREEN: 'OTP_VERIFICATION_SCREEN',
  CHANGE_PASSWORD_SCREEN: 'CHANGE_PASSWORD_SCREEN',
  EMAIL_VERIFICATION: 'EMAIL_VERIFICATION',
  REG_EMAIL_VERIFICATION: 'REG_EMAIL_VERIFICATION',
  REG_MOBILE_VERIFICATION: 'REG_MOBILE_VERIFICATION',
  // auth

  // customer screen
  SEARCH_LOCATION: 'SEARCH_LOCATION',
  FAVOURITE_SCREEN: 'FAVOURITE_SCREEN',
  CUSTOMER_PROFILE_SCREEN: 'CUSTOMER_PROFILE_SCREEN',
  CHEF_LIST_SCREEN: 'CHEF_LIST_SCREEN',
  CHECK_AVAILABILITY: 'CHECK_AVAILABILITY',
  PRICING_MODAL: 'PRICING_MODAL',
  BOOK_NOW: 'BOOK_NOW',
  CUSTOMER_PAYMENT_HISTORY: 'CUSTOMER_PAYMENT_HISTORY',
  CUSTOMER_PREFERENCE: 'CUSTOMER_PREFERENCE',
  ADDRESS: 'ADDRESS',
  ALLERGIES: 'ALLERGIES',
  DIETARY: 'DIETARY',
  FAVOURITE_CUISINE: 'FAVOURITE_CUISINE',
  KITCHEN_EQUIPMENT: 'KITCHEN_EQUIPMENT',
  DISPLAY_PICTURE: 'DISPLAY_PICTURE',
  CUSTOMER_EDIT_PROFILE: 'CUSTOMER_EDIT_PROFILE',
  BOOK_PRICE: 'BOOK_PRICE',
  BOOK_DIETARY: 'BOOK_DIETARY',
  BOOK_ALLERGY: 'BOOK_ALLERGY',
  BOOK_KITCHEN_EQUIPMENT: 'BOOK_KITCHEN_EQUIPMENT',
  EXTRA_PAYMENT: 'EXTRA_PAYMENT',
  CHANGE_BOOK_LOCATION: 'CHANGE_BOOK_LOCATION',
  CUSTOMER_CONTENT: 'CUSTOMER_CONTENT',
  // customer screen

  // chef screen
  BOOKING_REQUEST_SCREEN: 'BOOKING_REQUEST_SCREEN',
  PAYMENTS_SCREEN: 'PAYMENTS_SCREEN',
  CHEF_PROFILE_SCREEN: 'CHEF_PROFILE_SCREEN',
  CHEF_SETTING_SCREEN: 'CHEF_SETTING_SCREEN',
  SET_AVAILABILITY_SCREEN: 'SET_AVAILABILITY_SCREEN',
  SET_UNAVAILABILITY_SCREEN: 'SET_UNAVAILABILITY_SCREEN',
  CHEF_SETUP_PROFILE: 'CHEF_SETUP_PROFILE',
  CHEF_MANAGE_PAYMENTS: 'CHEF_MANAGE_PAYMENTS',
  GALLERY_ATTACHMENT: 'GALLERY_ATTACHMENT',
  STRIPE_WEB_VIEW: 'STRIPE_WEB_VIEW',
  INTRO_MESSAGE: 'INTRO_MESSAGE',
  RATE_SERVICE: 'RATE_SERVICE',
  OPTION_LIST: 'OPTION_LIST',
  CHEF_EXPERIENCE: 'CHEF_EXPERIENCE',
  PRICE_CALCULATION: 'PRICE_CALCULATION',
  REGISTER_PROFILE: 'REGISTER_PROFILE',
  COMPLEXITY: 'COMPLEXITY',
  AWARDS: 'AWARDS',
  GALLERY: 'GALLERY',
  ATTACHMENT: 'ATTACHMENT',
  AVAILABILITY: 'AVAILABILITY',
  CHEF_EDIT_PROFILE: 'CHEF_EDIT_PROFILE',
  CHEF_REQUEST_PRICE: 'CHEF_REQUEST_PRICE',
  // chef screen

  // common
  NOTIFICATION_SCREEN: 'NOTIFICATION_SCREEN',
  CARD_MANAGEMENT: 'CARD_MANAGEMENT',
  BOOKING_HISTORY: 'BOOKING_HISTORY',
  BOOKING_DETAIL_SCREEN: 'BOOKING_DETAIL_SCREEN',
  SET_LOCATION_SCREEN: 'SET_LOCATION_SCREEN',
  BASIC_EDIT_PROFILE: 'BASIC_EDIT_PROFILE',
  FEEDBACK_SCREEN: 'FEEDBACK_SCREEN',
  FILTER_SCREEN: 'FILTER_SCREEN',
  NOTIFICATION_SETTINGS_SCREEN: 'NOTIFICATION_SETTINGS_SCREEN',
  ABOUT_US: 'ABOUT_US',
  CONTACT_US: 'CONTACT_US',
  TERMS_AND_POLICY: 'TERMS_AND_POLICY',
  CONVERSATION_LIST: 'CONVERSATION_LIST',
  BOOKING_NOTES_DETAIL_SCREEN: 'BOOKING_NOTES_DETAIL_SCREEN',
  CHAT_DETAIL: 'CHAT_DETAIL',
  CHEF_PRICING: 'CHEF_PRICING',
  ACCOUNT_SETTING: 'ACCOUNT_SETTING',
  CHEF_ACCOUNT: 'CHEF_ACCOUNT',
  // common
}
