export default {
  EMAIL: 'Email',
  PASSWORD: 'Password',
  KEEP_ME_LOGGED_IN: 'Keep me logged in',
  ARE_YOU_CHEF: 'Are you chef?',
  FORGOT_PASSWORD: 'Forgot Password?',
  FIRST_NAME: 'First Name',
  LAST_NAME: 'Last Name',
  DOB: 'Date of Birth',
  PASSWORD: 'Password',
  CONFIRM_PASSWORD: 'Confirm Password',
  MOBILE_NUMBER: 'Mobile Number',
  I_AM_A_CHEF: 'I am a Chef',
  EMAIL_INPUT: 'email',
  PASSWORD_INPUT: 'password',
  EMAIL_PLACEHOLDER: 'Enter your Email Address',
  PASSWORD_PLACEHOLDER: 'Enter your password',
  FORM_CONTROL: 'form-control',
  FIRST_NAME_PLACEHOLDER: 'Enter your first name',
  LAST_NAME_PLACEHOLDER: 'Enter your last name',
  CONFIRM_PASSWORD_PLACEHOLDER: 'Re-enter password',
  MOBILE_NUMBER_PLACEHOLDER: 'Enter your mobile number',
  TEXT: 'text',
  CHANGE_PASSWORD: 'Change Password',
  CURRENT_PASSWORD_TITLE: 'Enter your Current password',
  CURRENT_PASSWORD_PLACE_HOLDER: 'Enter Current Password',
  NEW_PASSWORD_TITLE: 'Enter new password',
  NEW_PASSWORD_PLACE_HOLDER: 'Enter New Password',
  CONFIRM_NEW_PASSWORD_PLACE_HOLDER: 'Enter Confirm New Password',
  PASSWORD_INPUT: 'password',
  TEXT: 'text',
  UPDATE: 'Update',
  FORGOT_PASSWORD: 'Forgot Password',
  SUBMIT_MESSAGE:
    'Please submit the email address associated with your account and we will send you a link to reset password',
  EMAIL_PLACE_HOLDER: 'Enter your email',
  REFERRAL_EMAIL_PLACE_HOLDER: 'Enter your referral Email Address',
  REFERRAL: 'referrel',
  REFERRAL_LABEL: 'Referral Email',
  RESET_PASSWORD: 'Reset Password',
  ENTER_YOUR_OTP: 'Enter your OTP',
  BLOCK_MESSAGE: 'Your account is blocked by admin',
  MODAL_MESSAGE: 'Please enter email id for facebook login!',
  FB_LOGOUT_ERROR:
    'This Account does not have email address. please try to register with this Google/Facebook account',
};
