export default {
  I_AM_A_CHEF: 'Register as Chef',
  I_AM_A_CUSTOMER: 'Register as Customer',
  CHEF_HAT: require('../../../images/mock-image/chef-register-modal.png'),
  YES: 'Yes',
  NO: 'No',
  SUCCESS_MSG: 'You accepted customer request',
  CUSTOMER_REQUESTED: 'CUSTOMER_REQUESTED',
  CHEF_ACCEPTED: 'CHEF_ACCEPTED',
  CHEF_ACCEPTED_TEXT: 'Chef Accepted',
  CHEF_REJECTED: 'CHEF_REJECTED',
  CANCELLED_BY_CHEF: 'CANCELLED_BY_CHEF',
  CANCELLED_BY_CHEF_OR_CHEF_REJECTED: 'CANCELLED_BY_CHEF/CHEF_REJECTED',
  CANCELLED_BY_CHEF_OR_CHEF_REJECTED_TEXT: 'You have Cancelled Booking / You have Rejected Booking',
  CANCELLED_BY_CUSTOMER: 'CANCELLED_BY_CUSTOMER',
  CANCELLED_BY_CUSTOMER_TEXT: 'Cancelled by Customer',
  CANCELLED_BY_CUSTOMER_TEXT1: 'You have Cancelled Booking',
  COMPLETED: 'COMPLETED',
  Complete: 'Complete',
  UPCOMING: 'Upcoming',
  CANCEL: 'Cancel',
  ACCEPTED: 'Accepted',
  Rejected: 'Rejected',
  ACCEPT: 'Accept',
  Reject: 'Reject',
  COMPLETED_BY_CUSTOMER: 'Completed by Customer',
  COMPLETED_BY_CHEF: 'Completed by Chef',
  ACCEPTED_BY_CHEF: 'Accepted by chef',
  REQUESTED_BY_CUSTOMER: 'Requested by Customer',
  AWAITING_FOR_CHEF: 'Awaiting For Chef',
  REASON: 'REASON',
  REQUIRED_REASON: 'Reason field is required',
  REASON_PLACE_HOLDER: 'Enter your reason',
  CONTINUE_LOGIN: 'Please login to proceed',
  EMAIL_PLACEHOLDER: 'Enter your Email Address',
  EMAIL: 'EMAIL',
  EMAIL_INPUT: 'email',
  FORM_CONTROL: 'form-control',
  SUBMIT: 'Submit',
  CUSTOMER_NOTES: `Customer's notes:`,
  GIVE_YOUR_NOTES:
    'Please enter dish names you wanna to cook. It will be displayed to chef and he/she may reply with list of ingredients. Thanks',
  ENTER_NOTES: 'Enter notes:',
  NO_OF_MINUTES_FOR_BOOKING_CANCEL: 'NO_OF_MINUTES_FOR_BOOKING_CANCEL',
  CANCEL_ALERT_MESSAGE: 'You cannot cancel now!',
  DISHES: 'Dishes:',
  NO_NOTES: 'No notes data are available',
  NOTES_ADDED_SUCCESS: 'Notes added successfully',
  BOOKING_COMPLETED: 'Booking completed successfully',
  STRIPEID_MISSING_MSG: 'Please add your card for payment updation!',
  COMPLETED_VALIDATION: `You can't complete booking before booking start date!`,
};
