export default {
  BOOKING_NOW: 'Booking Now',
  BOOKING_DATE: 'BOOKING DATE',
  BOOKING_DATE_PLACE_HOLDER: 'Enter Booking Date',
  BOOKING_TIME: 'BOOKING TIME',
  SELECTED_TIME: 'SELECTED TIME',
  PRICE: 'PRICE PER HOUR',
  TOTAL_PRICE: 'TOTAL PRICE',
  HOURS_COUNT: 'HOURS COUNT',
  TOTAL_PRICE_PLACEHOLDER: 'Enter total amount',
  HOURS_COUNT: 'HOURS COUNT',
  EMAIL: 'EMAIL',
  EMAIL_PLACE_HOLDER: 'Enter your email',
  SUBMIT: 'SUBMIT',
  RETRY_PAYMENT: 'RETRY PAYMENT',
  RETRY_PAYMENT_SMALL: 'Retry Payment',
  SUCCESS_MSG: 'Booking created Successfully',
  DISHES_SUCCESS_MSG: 'Dish added to list',
  PAYMENT_COMPLETED: 'Payment completed successfully',
  DATE_AVAILABLE: 'Please select a future date',
  TIME_AVAILABLE: 'Please select a future time',
  CARD_AVAIALABLE: 'Please select the card for payment purpose',
  COMMISSION_STRING: 'BOOKING_SERVICE_CHARGE_IN_PERCENTAGE',
  SERVICE_CHARGE: 'SERVICE CHARGE',
  TOTAL_HOURS_PRICE: 'TOTAL HOURS PRICE',
  NOTES: 'Notes',
  ABOUT_EVENT: 'About Event',
  DISHES: 'DISHES',
  BOOKING_DETAILS: 'BOOKING DETAILS:',
  AVAIALABLE_TIME: 'AVAILABLE TIME:',
  NOTES_PLACE_HOLDER:
    'Please enter dish names you wanna to cook. It will be displayed to chef and he/she may reply with list of ingredients. Thanks',
  NOTES_PLACE_HOLDER2: 'Tell a little bit about yourself and the event',
  YES: 'Yes',
  NO: 'No',
  SUBMIT_ALERT: 'Are you want to submit your booking?',
  MINIMUM_MINUTES_ALERT: `Sorry, Minimum booking`,
  HOUR: 'hour',
  HOURS: 'hours',
  MINIMUM_BOOKING_HOUR: 'MINIMUM BOOKING HOUR(S):',
  LOCATION_NOTES: 'NOTES: Please select location around x miles from chef location',
};
