export default {
  CUSTOMER_REQUESTED: 'CUSTOMER_REQUESTED',
  CHEF_ACCEPTED: 'CHEF_ACCEPTED',
  CHEF_REJECTED: 'CHEF_REJECTED',
  CANCELLED_BY_CHEF: 'CANCELLED_BY_CHEF',
  CANCELLED_BY_CHEF_OR_CHEF_REJECTED: 'CANCELLED_BY_CHEF/CHEF_REJECTED',
  CANCELLED_BY_CUSTOMER: 'CANCELLED_BY_CUSTOMER',
  PAYMENT_PENDING: 'PAYMENT_PENDING',
  PAYMENT_FAILED: 'PAYMENT_FAILED',
  TRANSFER_FAILED: 'TRANSFER_FAILED',
  AMT_TRANSFER_FAILED: 'AMOUNT_TRANSFER_FAILED',
  AMT_TRANSFER_SUCCESS: 'AMOUNT_TRANSFER_SUCCESS',
  COMPLETED: 'COMPLETED',
  SUBMIT: 'Submit',
  SUBMIT_FEEDBACK: 'Submit your feedback',
  CANCEL: 'Cancel',
  Rejected: 'Rejected',
  ACCEPTED: 'Accepted',
  REJECT: 'Reject',
  ACCEPT: 'Accept',
  COMPLETE: 'Complete',
  EDIT: 'Edit',
  PAY_NOW: 'Pay Now',
  COMPLETED_ALERT: 'Are you sure you want to Complete?',
  ACCEPT_ALERT: 'Are you sure you want to accept this request?',
  REJECT_ALERT: 'Are you sure you want to reject this request?',
  CANCEL_ALERT: 'Are you sure you want to cancel this request?',
  CHEF_REQUESTED_AMOUNT: 'CHEF_REQUESTED_AMOUNT',
  CHE_REQUESTED_AMOUNT_STRING: 'Chef requested amount',
  STRIPEID_MISSING_MSG: 'Please add your card for payment updation!',
  COMPLETED_VALIDATION: `You can't complete booking before booking start date!`,
};
