export default {
  GOOGLEAPI: 'https://maps.googleapis.com/maps/api/geocode/json?latlng=',
  KEY: '&key=',
  TEXT: 'text',
  NUMBER: 'number',
  EDIT_LOCATION_INFORMATION: 'Location Information',
  LOCATION: 'Location',
  ENTER_FULL_ADDRESS: 'Enter Full address',
  ADDRESS: 'address',
  ENTER_APARTMENT_NAME: 'Enter Apartment name',
  STREET_ADDRESS: 'streetAddress',
  PLEASE_ENTER_APARTMENT_NAME: 'Please enter Apartment name',
  ENTER_HOUSE_NO: 'Enter House No.',
  PLEASE_ENTER_HOUSE_NO: 'Please enter House No.',
  HOUSE_NO: 'houseNo',
  ENTER_ZIPCODE: 'Enter Zipcode',
  PLEASE_ENTER_ZIPCODE: 'Please enter Zipcode',
  ZIPCODE: 'zipcode',
  ENTER_DISTANCE: 'How much distance you can travel to provide service?(KM)',
  PLEASE_ENTER_DISTANCE: 'Please enter distance',
  DISTANCE: 'distance',
};
