/** @format */
export const CONFIG = {
  //Firefabase config
  FIREBASE_API_KEY: 'FIREBASE_API_KEY',
  AUTHDOMAIN: 'AUTHDOMAIN',
  DATABASEURL: 'DATABASEURL',
  PROJECTID: 'PROJECTID',
  MESSAGINGSENDERID: 'MESSAGINGSENDERID',
  APPID: 'APPID',

  //Gql
  GQL_ENDPOINT_URI: 'GQL_ENDPOINT_URI',
  EDIT_PROFILE_URL: 'EDIT_PROFILE_URL',
}
